name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: cargo build --verbose --release
    - name: Upload linux executable
      uses: actions/upload-artifact@v1
      with:
        name: mcAnalysis
        path: target/release/minecraft_analysis
  
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: cargo build --verbose --release
    - name: Upload windows executable
      uses: actions/upload-artifact@v1
      with:
        name: mcAnalysis.exe
        path: target/release/minecraft_analysis.exe
